name: Build and deploy demo-app

on:
  push:
    branches: [trunk]
    paths:
      - "test/**"
      - ".github/workflows/build-deploy-demo-app.yml"
      - ".github/deploy/values-demo-app.yaml"
  pull_request:
    branches: [trunk]
    paths:
      - "test/**"
      - ".github/workflows/build-deploy-demo-app.yml"
      - ".github/deploy/values-demo-app.yaml"

permissions:
  actions: read
  contents: read
  id-token: write
  security-events: write
  issues: read
  checks: write
  pull-requests: write

jobs:
  # unittests:
  #   name: Unit Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: 3lvia/core-github-actions-templates/unittest@trunk

  # analyze:
  #   name: Analyze
  #   runs-on: ubuntu-latest
  #   if: github.ref != 'refs/heads/trunk' # only run analyze on PR
  #   steps:
  #     - uses: 3lvia/core-github-actions-templates/analyze@trunk

  build:
    name: Build and Scan
    runs-on: ubuntu-latest
    environment: build
    steps:
      - uses: 3lvia/core-github-actions-templates/build@trunk
        with:
          name: demo-app
          namespace: core
          dockerfile: test/Dockerfile
          AZURE_CLIENT_ID: ${{ vars.ACR_CLIENT_ID }}

  deploy_dev:
    name: Deploy Dev
    needs: [build]
    runs-on: ubuntu-latest
    environment: dev
    if: github.ref == 'refs/heads/trunk'
    steps:
      - uses: 3lvia/core-github-actions-templates/deploy@trunk
        with:
          name: demo-app
          namespace: core
          environment: dev
          AZURE_CLIENT_ID: ${{ vars.AKS_CLIENT_ID }}
          helm-values-path: '.github/deploy/values-demo-app.yaml'

  # deploy_test:
  #   name: Deploy Test
  #   needs: [deploy_dev]
  #   runs-on: ubuntu-latest
  #   environment: test
  #   if: github.ref == 'refs/heads/trunk'
  #   steps:
  #     - uses: 3lvia/core-github-actions-templates/deploy@trunk
  #       with:
  #         name: demo-app
  #         namespace: core
  #         environment: test
  #         AZURE_CLIENT_ID: ${{ vars.AKS_CLIENT_ID }}
  #         helm-values-path: '.github/deploy/values-demo-app.yaml'

  # deploy_prod:
  #   name: Deploy Prod
  #   needs: [deploy_test]
  #   runs-on: ubuntu-latest
  #   environment: prod
  #   if: github.ref == 'refs/heads/trunk'
  #   steps:
  #     - uses: 3lvia/core-github-actions-templates/deploy@trunk
  #       with:
  #         name: demo-app
  #         namespace: core
  #         environment: prod
  #         AZURE_CLIENT_ID: ${{ vars.AKS_CLIENT_ID }}
  #         helm-values-path: '.github/deploy/values-demo-app.yaml'
